### ISSUE TITLE
Color Scheme entwerfen

### ISSUE THREAD

**Issue by finnholzgrabe** [Pudl0/westerloy#5]
Für die Website soll übergreifend ein einheitliches Aussehen geschaffen werden, also müssen Dinge wie:

- Primary Color
- Secondary Color
- Base Color
- Accent Color
- Action / Non Action

Und was sonst alles so dazu gehört einmal gesammelt werden, sodass dann darüber entschieden werden kann.

**Comment by Pudl0** [comment]
Habe mich für folgende Palette entschieden.

https://coolors.co/palette/fec5bb-fcd5ce-fae1dd-f8edeb-e8e8e4-d8e2dc-ece4db-ffe5d9-ffd7ba-fec89a

Ich werde das neue Schema soweit einrichten und euch dann nach Feedback fragen.
