### ISSUE TITLE
Logo must lead to start page

### ISSUE THREAD

**Issue by FenjaB** [Pudl0/westerloy#62]
### Motivation

Right now, the logo is not leading back to the start page. That's a huge usability problem!

---

### Acceptance criteria

- [x] logo leads to start page

---

### Technical solutions

/

---

### Attachments

/

**Comment by Pudl0** [comment]
This will get addressed in https://github.com/Pudl0/westerloy/issues/49 since i am rewriting the navmenu anyways. I will link the pr.
